sonar.projectKey=LibraryManagementSystem
sonar.projectName=Library Management System
sonar.projectVersion=1.0
sonar.sources=.
sonar.java.binaries=.
sonar.host.url=http://localhost:9000

# Use the token here instead of login/password
sonar.token=sqa_3e1bd93597469a5aa3788c68ef5a72f6cfc2d0d6